refactor apt-install

diff --git a/rootfs/sbin/apt-install b/rootfs/sbin/apt-install
--- a/rootfs/sbin/apt-install
+++ b/rootfs/sbin/apt-install
@@ -1,45 +1,35 @@
-#!/bin/sh
+#!/usr/bin/env bash
+################################################################################
+# This is property of eXtremeSHOK.com
+# You are free to use, modify and distribute, however you may not remove this notice.
+# Copyright (c) Adrian Jon Kriel :: admin@extremeshok.com
+################################################################################
+#
+# Wrapped function for apt-get update && apt-get install && apt-get clean
+# will automatically retry a failed apt-install where the package failes to download
+#
+################################################################################
 # Retry install packages
-max_retries=30
+max_retries=12
 current_retries=0
+sleep_between_retries=5
+
 apt-get update
 
-until apt-get -q -y -o Dpkg::Options::="--force-confmiss" -o DPkg::Options::="--force-confold" -o DPkg::Options::="--force-confdef" install --no-install-recommends "$@"; do
-  # ret="$?"
-  # if [ "$ret" -eq "100" ] ; then
-  #   # package not found "Unable to locate package"
-  #   break
-  # fi
+# save error message (stderr) to error and display output (stdout)
+until { error=$(apt-get -q -y -o Dpkg::Options::="--force-confmiss" -o DPkg::Options::="--force-confold" -o DPkg::Options::="--force-confdef" install --no-install-recommends "$@" 2>&1 1>&$out); } {out}>&1 >output ; do
+  ret="$?"
+  if [[ "$error" == *"Unable to locate package"* ]] ; then
+    echo "${error/E: /}"
+    exit "$ret"
+  fi
   current_retries=$((current_retries + 1))
   if [ $current_retries -gt $max_retries ] ; then
     echo "ERROR: max retries of ${max_retries} reached"
-    break
+    exit "1"
   fi
-  echo "== Install package/s failed, retrying ${current_retries}/${max_retries} =="
-  sleep 5
+  echo "== Install of package/s failed, retrying ${current_retries}/${max_retries} =="
+  sleep "$sleep_between_retries"
 done
+
 apt-get clean
-# 
-# OUTPUT="";
-# while [ ""`echo $OUTPUT | grep -c somestring` != 0 ]; do
-#   result="$(apt-get -q -y -o Dpkg::Options::="--force-confmiss" -o DPkg::Options::="--force-confold" -o DPkg::Options::="--force-confdef" install --no-install-recommends "$@")"
-# done
-#
-#
-#
-# until [ "$ret" -eq "0" ]; do
-#   ret="$?"
-#   if [ "$ret" -eq "100" ] ; then
-#     if [ echo "$result" | grep -q "Unable to locate package" ] ; then
-#       break
-#     fi
-#   fi
-#   current_retries=$((current_retries + 1))
-#   if [ $current_retries -gt $max_retries ] ; then
-#     echo "ERROR: max retries of ${max_retries} reached"
-#     break
-#   fi
-#   echo "== Install package/s failed, retrying ${current_retries}/${max_retries} =="
-#   sleep 5
-# done
-# apt-get clean
